# Generated by Django 3.1.5 on 2021-05-12 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(default='', max_length=50, verbose_name='Symbol')),
                ('company', models.CharField(default='Other company', max_length=50, verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='WorldIndices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Index')),
                ('file', models.CharField(max_length=50, verbose_name='File')),
            ],
        ),
        migrations.CreateModel(
            name='WorldIndicesInfo',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='timestamp_symbol')),
                ('open_price', models.DecimalField(decimal_places=2, default=None, max_digits=11, verbose_name='Open')),
                ('high_price', models.DecimalField(decimal_places=2, default=None, max_digits=11, verbose_name='High')),
                ('low_price', models.DecimalField(decimal_places=2, default=None, max_digits=11, verbose_name='Low')),
                ('close_price', models.DecimalField(decimal_places=2, default=None, max_digits=11, verbose_name='Close')),
                ('adj_close_price', models.DecimalField(decimal_places=2, default=None, max_digits=11, verbose_name='Adj Close')),
                ('volume', models.IntegerField(default=None, verbose_name='Volume')),
                ('date', models.DateTimeField(default=None, verbose_name='Date')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_set', to='stock.worldindices')),
            ],
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='timestamp_symbol')),
                ('open_price', models.DecimalField(decimal_places=2, default=None, max_digits=11, verbose_name='Open')),
                ('high_price', models.DecimalField(decimal_places=2, default=None, max_digits=11, verbose_name='High')),
                ('low_price', models.DecimalField(decimal_places=2, default=None, max_digits=11, verbose_name='Low')),
                ('close_price', models.DecimalField(decimal_places=2, default=None, max_digits=11, verbose_name='Close')),
                ('adj_close_price', models.DecimalField(decimal_places=2, default=None, max_digits=11, verbose_name='Adj Close')),
                ('volume', models.IntegerField(default=None, verbose_name='Volume')),
                ('date', models.DateTimeField(default=None, verbose_name='Date')),
                ('change', models.DecimalField(decimal_places=2, default=None, max_digits=11, verbose_name='change')),
                ('change_percent', models.DecimalField(decimal_places=2, default=None, max_digits=11, verbose_name='change_percent')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_set', to='stock.stock')),
            ],
        ),
    ]
